### ISSUE TITLE
Accept URI as param and generate link automatically

### ISSUE THREAD

**Issue by klibby** [anarute/mxrtodxr#1]
Great start, but what we ultimately need is for the page to be able to convert the URI on the fly, without the user having to input anything. That is, Apache will have a redirect rule that sends everything to this page and passes in the original URI as a parameter (or multiple, if that's of use). The page then takes that, does magic, and supplies that as it's best guess.

The goal is for users to visit an mxr.mozilla.org link, land on this page, see some warnings and have a link that they can immediately click to carry on to dxr.mozilla.org. (Even that seems to be overly onerous for some, so requiring them to cut&paste a URL would be impossible.)

**Comment by anarute** [comment]
Thanks fubar for the feedback. The idea of the input is for us to test and
sharpen the guessing function with all possible URIs before putting it in
production. It is temporary and as soon as we achieve the expected results,
we can remove the input and take the URL automatically using
`window.location`.
I will also add a function to take the referrer URL and check if the user
comes from BMO so we can redirect them automatically.

**Comment by klibby** [comment]
Fantastic. I thought that might be what you were doing, but wanted to make sure I was right in thinking so.
